### ISSUE TITLE
Bacon

### ISSUE THREAD

**Issue by ghost** [clodoaldo-favaro/github-blog-posts#2]
Shank landjaeger sirloin prosciutto, pork burgdoggen ham biltong. Cupim ham hock bresaola ribeye chicken biltong sausage. Doner ball tip landjaeger bresaola leberkas. Meatball bacon shank short loin hamburger pork rump doner, buffalo tri-tip. Pig flank shank corned beef ribeye sirloin frankfurter prosciutto chicken short ribs biltong ham drumstick. Shankle drumstick cow hamburger, flank venison fatback chicken corned beef doner filet mignon brisket. Pancetta venison fatback prosciutto short ribs leberkas porchetta shoulder jerky tri-tip burgdoggen bresaola pig short loin.

**Comment by clodoaldo-favaro** [comment]
ASDASD
